//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
//::                                                                         ::
//::     Antonio Manuel Rodrigues Manso                                      ::
//::                                                                         ::
//::     I N S T I T U T O    P O L I T E C N I C O   D E   T O M A R        ::
//::     Escola Superior de Tecnologia de Tomar                              ::
//::     e-mail: manso@ipt.pt                                                ::
//::     url   : http://orion.ipt.pt/~manso                                  ::
//::                                                                         ::
//::     This software was build with the purpose of investigate and         ::
//::     learning.                                                           ::
//::                                                                         ::
//::                                                               (c)2015   ::
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//////////////////////////////////////////////////////////////////////////////
package p2p;

import curriculum.vitae.core.Certificado;
import curriculum.vitae.gui.CurriculumVitae;
import java.net.InetAddress;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import miner.Miner;
import utils.Block;
import utils.BlockChain;
import utils.GuiUtils;
import utils.RMI;

/**
 *
 * @author zulu
 */
public class NodeP2PGui extends javax.swing.JFrame implements P2Plistener {

    OremoteP2P myremoteObject;

    /**
     * Creates new form MessengerGUI
     */
    public NodeP2PGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtExceptionLog = new javax.swing.JLabel();
        txtTimeLog = new javax.swing.JLabel();
        txtTitleLog = new javax.swing.JLabel();
        pnMain = new javax.swing.JTabbedPane();
        pnServer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btStartServer = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtServerListeningPort = new javax.swing.JTextField();
        txtServerListeningObjectName = new javax.swing.JTextField();
        imgServerRunning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerLog = new javax.swing.JTextPane();
        pnP2PNetwork = new javax.swing.JPanel();
        btStartClient = new javax.swing.JButton();
        txtServerAdress = new javax.swing.JTextField();
        txtServerPort = new javax.swing.JTextField();
        txtServerObjectName = new javax.swing.JTextField();
        imgClientRunning = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNetwork = new javax.swing.JTextPane();
        pnCertificado = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtListTransdactions = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtLogMining = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        lblMining = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();
        pnBlockchain = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtBlockHeader = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBlockCertificados = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstBlcockchain = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExceptionLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtExceptionLog.setForeground(new java.awt.Color(255, 51, 102));
        txtExceptionLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExceptionLog.setText("Network node");
        txtExceptionLog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel15.add(txtExceptionLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 0, 210, -1));

        txtTimeLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTimeLog.setText("00:00:00.000");
        jPanel15.add(txtTimeLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txtTitleLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitleLog.setText("                                                     ");
        jPanel15.add(txtTitleLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        getContentPane().add(jPanel15, java.awt.BorderLayout.SOUTH);

        pnServer.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout(10, 10));

        btStartServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/startServer.png"))); // NOI18N
        btStartServer.setText("Start");
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });
        jPanel3.add(btStartServer, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        txtServerListeningPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerListeningPort.setText("10010");
        txtServerListeningPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Port Number"));
        txtServerListeningPort.setPreferredSize(new java.awt.Dimension(200, 36));
        jPanel7.add(txtServerListeningPort);

        txtServerListeningObjectName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerListeningObjectName.setText("remoteP2P");
        txtServerListeningObjectName.setBorder(javax.swing.BorderFactory.createTitledBorder("ObjectName"));
        jPanel7.add(txtServerListeningObjectName);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        imgServerRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/loading_green.gif"))); // NOI18N
        imgServerRunning.setEnabled(false);
        jPanel3.add(imgServerRunning, java.awt.BorderLayout.EAST);

        pnServer.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        txtServerLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Server"));
        txtServerLog.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtServerLog);

        pnServer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnMain.addTab("Server", new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/Connect_to_Server.png")), pnServer); // NOI18N

        btStartClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/startClient.jpg"))); // NOI18N
        btStartClient.setText("Connect");
        btStartClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartClientActionPerformed(evt);
            }
        });

        txtServerAdress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerAdress.setText("127.0.0.1");
        txtServerAdress.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Adress"));
        txtServerAdress.setPreferredSize(new java.awt.Dimension(200, 36));

        txtServerPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerPort.setText("10010");
        txtServerPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Port Number"));
        txtServerPort.setPreferredSize(new java.awt.Dimension(200, 36));

        txtServerObjectName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerObjectName.setText("remoteP2P");
        txtServerObjectName.setBorder(javax.swing.BorderFactory.createTitledBorder("Object Name"));

        imgClientRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/loading_blue.gif"))); // NOI18N
        imgClientRunning.setEnabled(false);

        txtNetwork.setEditable(false);
        txtNetwork.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Network"));
        jScrollPane3.setViewportView(txtNetwork);

        javax.swing.GroupLayout pnP2PNetworkLayout = new javax.swing.GroupLayout(pnP2PNetwork);
        pnP2PNetwork.setLayout(pnP2PNetworkLayout);
        pnP2PNetworkLayout.setHorizontalGroup(
            pnP2PNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnP2PNetworkLayout.createSequentialGroup()
                .addComponent(btStartClient, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnP2PNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtServerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServerObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgClientRunning, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
            .addGroup(pnP2PNetworkLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        pnP2PNetworkLayout.setVerticalGroup(
            pnP2PNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnP2PNetworkLayout.createSequentialGroup()
                .addGroup(pnP2PNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnP2PNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btStartClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnP2PNetworkLayout.createSequentialGroup()
                            .addComponent(txtServerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtServerObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnP2PNetworkLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(imgClientRunning, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnMain.addTab("P2pNetwork", new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/p2p_32.png")), pnP2PNetwork); // NOI18N

        pnCertificado.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        txtListTransdactions.setEditable(false);
        txtListTransdactions.setColumns(20);
        txtListTransdactions.setRows(5);
        txtListTransdactions.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Transactions"));
        jScrollPane4.setViewportView(txtListTransdactions);

        jPanel12.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.BorderLayout());

        txtLogMining.setEditable(false);
        txtLogMining.setColumns(20);
        txtLogMining.setRows(5);
        txtLogMining.setBorder(javax.swing.BorderFactory.createTitledBorder("Miner Log"));
        jScrollPane5.setViewportView(txtLogMining);

        jPanel11.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new java.awt.BorderLayout());

        lblMining.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/working.gif"))); // NOI18N
        lblMining.setText("mining");
        jPanel13.add(lblMining, java.awt.BorderLayout.CENTER);

        lblWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/winner.gif"))); // NOI18N
        jPanel13.add(lblWinner, java.awt.BorderLayout.EAST);

        jPanel11.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel10, java.awt.BorderLayout.WEST);

        pnCertificado.add(jPanel12, java.awt.BorderLayout.CENTER);

        pnMain.addTab("Certificado", new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/transaction_32.png")), pnCertificado); // NOI18N

        pnBlockchain.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Block Data"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane7.setPreferredSize(new java.awt.Dimension(252, 105));

        txtBlockHeader.setEditable(false);
        txtBlockHeader.setColumns(20);
        txtBlockHeader.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtBlockHeader.setRows(5);
        txtBlockHeader.setBorder(javax.swing.BorderFactory.createTitledBorder("Header"));
        jScrollPane7.setViewportView(txtBlockHeader);

        jPanel5.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Certficados"));

        txtBlockCertificados.setEditable(false);
        txtBlockCertificados.setColumns(20);
        txtBlockCertificados.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtBlockCertificados.setRows(5);
        jScrollPane6.setViewportView(txtBlockCertificados);

        jPanel8.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        pnBlockchain.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        lstBlcockchain.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstBlcockchain.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBlcockchainValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(lstBlcockchain);

        pnBlockchain.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        pnMain.addTab("Blockchain", new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/blockchain_32.png")), pnBlockchain); // NOI18N

        getContentPane().add(pnMain, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstBlcockchainValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstBlcockchainValueChanged
        try {
            BlockChain bc = myremoteObject.getBlockchain();
            int index = bc.getSize() - lstBlcockchain.getSelectedIndex() - 1;
            if (index < 0 || index >= bc.getSize()) {
                return;
            }
            Block selected = bc.get(index);
            txtBlockHeader.setText(selected.getHeaderString());
            txtBlockHeader.setCaretPosition(0);
            txtBlockCertificados.setText(selected.getCertificadosString());
            txtBlockCertificados.setCaretPosition(0);

        } catch (RemoteException ex) {
            onException(ex, "list selection");
        } catch (Exception ex) {
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lstBlcockchainValueChanged

    private void btStartClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartClientActionPerformed
        new Thread(() -> {
            try {
                imgClientRunning.setEnabled(true);
                String host = txtServerAdress.getText();
                int remotePort = Integer.parseInt(txtServerPort.getText());
                String remoteName = txtServerObjectName.getText();
                String address = String.format("//%s:%d/%s", host, remotePort, remoteName);
                IremoteP2P node = (IremoteP2P) RMI.getRemote(address);
                myremoteObject.addNode(node);
                //execute remote method
                myremoteObject.addMessage("Ligou-se à rede!");
                new CurriculumVitae(this, myremoteObject).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }//GEN-LAST:event_btStartClientActionPerformed

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartServerActionPerformed
        new Thread(() -> {
            try {
                int port = Integer.parseInt(txtServerListeningPort.getText());
                String name = txtServerListeningObjectName.getText();
                //local adress of server
                String host = InetAddress.getLocalHost().getHostAddress();
                //create registry to object
                LocateRegistry.createRegistry(port);
                //create adress of remote object
                String address = String.format("//%s:%d/%s", host, port, name);
                myremoteObject = new OremoteP2P(address, this);
                //link adress to object
                Naming.rebind(address, myremoteObject);
                onBlockchainUpdate(myremoteObject.getBlockchain());
            } catch (Exception ex) {
                onException(ex, "Starting server");
                Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }//GEN-LAST:event_btStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NodeP2PGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStartClient;
    private javax.swing.JButton btStartServer;
    private javax.swing.JLabel imgClientRunning;
    private javax.swing.JLabel imgServerRunning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblMining;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JList<String> lstBlcockchain;
    private javax.swing.JPanel pnBlockchain;
    private javax.swing.JPanel pnCertificado;
    private javax.swing.JTabbedPane pnMain;
    private javax.swing.JPanel pnP2PNetwork;
    private javax.swing.JPanel pnServer;
    private javax.swing.JTextArea txtBlockCertificados;
    private javax.swing.JTextArea txtBlockHeader;
    private javax.swing.JLabel txtExceptionLog;
    private javax.swing.JTextArea txtListTransdactions;
    private javax.swing.JTextArea txtLogMining;
    private javax.swing.JTextPane txtNetwork;
    private javax.swing.JTextField txtServerAdress;
    private javax.swing.JTextField txtServerListeningObjectName;
    private javax.swing.JTextField txtServerListeningPort;
    private javax.swing.JTextPane txtServerLog;
    private javax.swing.JTextField txtServerObjectName;
    private javax.swing.JTextField txtServerPort;
    private javax.swing.JLabel txtTimeLog;
    private javax.swing.JLabel txtTitleLog;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onStart(String message) {
        setTitle(message);
        imgServerRunning.setEnabled(true);
        btStartServer.setEnabled(false);
        GuiUtils.addText(txtServerLog, "Start server", message);
    }

    static DateTimeFormatter hfmt = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");

    @Override
    public void onException(Exception e, String title) {
        txtTimeLog.setText(LocalTime.now().format(hfmt));
        txtExceptionLog.setForeground(new java.awt.Color(255, 0, 0));
        txtExceptionLog.setText(e.getMessage());
        txtTitleLog.setText(title);
        //JOptionPane.showMessageDialog(this, e.getMessage(), title, JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void onConect(String address) {
        try {
            List<IremoteP2P> net = myremoteObject.getNetwork();
            for (IremoteP2P iremoteP2P : net) {
                GuiUtils.addText(txtNetwork, "Nó da rede", iremoteP2P.getAdress());
            }
            pnMain.setSelectedComponent(pnP2PNetwork);
        } catch (RemoteException ex) {
            onException(ex, "On conect");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onTransaction(String transaction) {
        try {
            onMessage(transaction);
            String txt = "";
            List<Certificado> tr = myremoteObject.getCertificados();
            for (Certificado certificado : tr) {
                txt += certificado.toString() + "\n";
            }
            //txtListCertificados.setText(txt);
            pnMain.setSelectedComponent(pnBlockchain);
        } catch (RemoteException ex) {
            onException(ex, "on transaction");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onMessage(String title) throws RemoteException {
        new Thread(() -> {
            try {
                List<String> list = myremoteObject.getMessages();
                for (String m : list) {
                    GuiUtils.addText(txtServerLog, myremoteObject.getAdress(), m);
                }
            } catch (RemoteException ex) {
                onException(ex, "on transaction");
                Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }

    @Override
    public void onStartMining(String message, int zeros) {
        SwingUtilities.invokeLater(() -> {
            pnMain.setSelectedComponent(pnCertificado);
            lblMining.setVisible(true);
            lblWinner.setVisible(false);
            txtLogMining.setText("[START]" + message + "[" + zeros + "]\n");
            lblMining.setText("mining " + zeros + " zeros");
            repaint();
        });
    }

    @Override
    public void onStopMining(String message, int nonce) {
        SwingUtilities.invokeLater(() -> {
            txtLogMining.setText("[STOP]" + message + "[" + nonce + "]\n" + txtLogMining.getText());
            lblMining.setVisible(false);
            pnMain.setSelectedComponent(pnCertificado);
            txtLogMining.setText("Nounce Found [" + nonce + "]\n" + txtLogMining.getText());
            System.out.println(" NONCE " + nonce + "\t" + message);
            repaint();
        });
    }

    @Override
    public void onNounceFound(String message, int nonce) {
        try {
            myremoteObject.stopMining(nonce);
        } catch (RemoteException ex) {
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.invokeLater(() -> {
            txtLogMining.setText("Nounce Found [" + nonce + "]\n" + txtLogMining.getText());
            lblMining.setVisible(false);
            lblWinner.setText(message);
            lblWinner.setVisible(true);
            pnMain.setSelectedComponent(pnCertificado);
            txtTitleLog.setText(Miner.getHash(myremoteObject.myMiner.getMessage(), myremoteObject.myMiner.getNonce()));
            repaint();
            System.out.println(" NONCE " + nonce + "\t" + message);
        });
    }

    @Override
    public void onBlockchainUpdate(BlockChain b) {
        SwingUtilities.invokeLater(() -> {
            DefaultListModel model = new DefaultListModel();
            for (int i = b.getSize() - 1; i >= 0; i--) {
                model.addElement(b.get(i));
            }
            lstBlcockchain.setModel(model);
            lstBlcockchain.setSelectedIndex(0);
            pnMain.setSelectedComponent(pnBlockchain);
            repaint();
        });
    }
}
