/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package curriculum.vitae.gui;

import curriculum.vitae.core.Lingua;
import curriculum.vitae.core.Utilizador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author joaob
 */
public class adicionarLinguas extends java.awt.Dialog {

    CurriculumVitae cv;
    Utilizador user;
    Lingua lingua = new Lingua("", "");
    ArrayList<JButton> buttons = new ArrayList<>();
    String auxLingua = "";
    

    /**
     * Creates new form adicionarDados
     */
    public adicionarLinguas(CurriculumVitae parent, boolean modal, Utilizador user) {
        super(parent, modal);
        this.cv = parent;
        this.user = user;
        initComponents();
        lbl_linguas.setText(user.getDados().getLinguas().toString());
        buttons.add(pt);
        buttons.add(en);
        buttons.add(it);
        buttons.add(uk);
        buttons.add(tr);
        buttons.add(es);
        buttons.add(ru);
        buttons.add(pl);
        buttons.add(ch);
        buttons.add(jp);
        buttons.add(fr);
        buttons.add(nl);
        buttons.add(gr);
        buttons.add(ar);
        buttons.add(kr);

//        for (int i = 0; i < buttons.size(); i++) {
//            auxLingua = buttons.get(i).getText();
//            final int index = i;
//            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_linguas = new javax.swing.JLabel();
        painelLinguas = new javax.swing.JPanel();
        pt = new javax.swing.JButton();
        en = new javax.swing.JButton();
        it = new javax.swing.JButton();
        uk = new javax.swing.JButton();
        tr = new javax.swing.JButton();
        es = new javax.swing.JButton();
        ru = new javax.swing.JButton();
        pl = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        jp = new javax.swing.JButton();
        fr = new javax.swing.JButton();
        nl = new javax.swing.JButton();
        gr = new javax.swing.JButton();
        ar = new javax.swing.JButton();
        kr = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Competências Linguísticas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Línguas Faladas (selecione a pretendida)");

        lbl_linguas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_linguas.setToolTipText("");

        painelLinguas.setLayout(new java.awt.GridLayout(3, 4));

        pt.setText("Português");
        pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptActionPerformed(evt);
            }
        });
        painelLinguas.add(pt);

        en.setText("English");
        en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enActionPerformed(evt);
            }
        });
        painelLinguas.add(en);

        it.setText("Italiano");
        it.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itActionPerformed(evt);
            }
        });
        painelLinguas.add(it);

        uk.setText("Українська (Ukrainska)");
        uk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukActionPerformed(evt);
            }
        });
        painelLinguas.add(uk);

        tr.setText("Türkçe");
        tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trActionPerformed(evt);
            }
        });
        painelLinguas.add(tr);

        es.setText("Espanõl");
        es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esActionPerformed(evt);
            }
        });
        painelLinguas.add(es);

        ru.setText("Русский (Russkiy)");
        ru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruActionPerformed(evt);
            }
        });
        painelLinguas.add(ru);

        pl.setText("Polski");
        pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plActionPerformed(evt);
            }
        });
        painelLinguas.add(pl);

        ch.setText("普通话 (Pǔtōnghuà)");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        painelLinguas.add(ch);

        jp.setText("日本語 (Nihongo)");
        jp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpActionPerformed(evt);
            }
        });
        painelLinguas.add(jp);

        fr.setText("Français");
        fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frActionPerformed(evt);
            }
        });
        painelLinguas.add(fr);

        nl.setText("Deutsch");
        nl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlActionPerformed(evt);
            }
        });
        painelLinguas.add(nl);

        gr.setText("Ελληνικά (Elliniká)");
        gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grActionPerformed(evt);
            }
        });
        painelLinguas.add(gr);

        ar.setText("العربية (Al-‘Arabīyah)");
        ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arActionPerformed(evt);
            }
        });
        painelLinguas.add(ar);

        kr.setText("한국어 (Hangugeo)");
        kr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krActionPerformed(evt);
            }
        });
        painelLinguas.add(kr);

        btnProximo.setText("Próximo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLinguas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(99, 99, 99)
                                .addComponent(btnProximo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_linguas)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_linguas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(painelLinguas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        lbl_linguas.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(pt.getText());
        redireciona();
    }//GEN-LAST:event_ptActionPerformed

    private void enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(en.getText());
        redireciona();
    }//GEN-LAST:event_enActionPerformed

    private void itActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(it.getText());
        redireciona();
    }//GEN-LAST:event_itActionPerformed

    private void ukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(uk.getText());
        redireciona();
    }//GEN-LAST:event_ukActionPerformed

    private void trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(tr.getText());
        redireciona();
    }//GEN-LAST:event_trActionPerformed

    private void esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(es.getText());
        redireciona();
    }//GEN-LAST:event_esActionPerformed

    private void ruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(ru.getText());
        redireciona();
    }//GEN-LAST:event_ruActionPerformed

    private void plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(pl.getText());
        redireciona();
    }//GEN-LAST:event_plActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(ch.getText());
        redireciona();
    }//GEN-LAST:event_chActionPerformed

    private void jpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(jp.getText());
        redireciona();
    }//GEN-LAST:event_jpActionPerformed

    private void frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(fr.getText());
        redireciona();
    }//GEN-LAST:event_frActionPerformed

    private void nlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(nl.getText());
        redireciona();
    }//GEN-LAST:event_nlActionPerformed

    private void grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(gr.getText());
        redireciona();
    }//GEN-LAST:event_grActionPerformed

    private void arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(ar.getText());
        redireciona();
    }//GEN-LAST:event_arActionPerformed

    private void krActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krActionPerformed
        // TODO add your handling code here:
        lingua.setLingua(kr.getText());
        redireciona();
    }//GEN-LAST:event_krActionPerformed

    private void redireciona() {
        dispose();
        new AdicionarCompetenciaLinguistica(cv, true, user, lingua).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnProximo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton ch;
    private javax.swing.JButton en;
    private javax.swing.JButton es;
    private javax.swing.JButton fr;
    private javax.swing.JButton gr;
    private javax.swing.JButton it;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jp;
    private javax.swing.JButton kr;
    private javax.swing.JLabel lbl_linguas;
    private javax.swing.JButton nl;
    private javax.swing.JPanel painelLinguas;
    private javax.swing.JButton pl;
    private javax.swing.JButton pt;
    private javax.swing.JButton ru;
    private javax.swing.JButton tr;
    private javax.swing.JButton uk;
    // End of variables declaration//GEN-END:variables
}
