/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package curriculum.vitae.gui;

import curriculum.vitae.core.Utilizador;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author joaob
 */
public class adicionarLinguas extends java.awt.Dialog {

    CurriculumVitae cv;
    Utilizador user;
    ArrayList<JCheckBox> listaOpcoes = new ArrayList<>();

    /**
     * Creates new form adicionarDados
     */
    public adicionarLinguas(CurriculumVitae parent, boolean modal, Utilizador user) {
        super(parent, modal);
        this.cv = parent;
        this.user = user;
        initComponents();
        listaOpcoes.add(checkAlemao);
        listaOpcoes.add(checkArabe);
        listaOpcoes.add(checkChines);
        listaOpcoes.add(checkCoreano);
        listaOpcoes.add(checkEspanhol);
        listaOpcoes.add(checkFrances);
        listaOpcoes.add(checkGrego);
        listaOpcoes.add(checkIngles);
        listaOpcoes.add(checkJapones);
        listaOpcoes.add(checkPolaco);
        listaOpcoes.add(checkPortugues);
        listaOpcoes.add(checkRusso);
        listaOpcoes.add(checkTurco);
        listaOpcoes.add(checkUcraniano);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelLinguas = new javax.swing.JPanel();
        checkPortugues = new javax.swing.JCheckBox();
        checkIngles = new javax.swing.JCheckBox();
        checkItaliano = new javax.swing.JCheckBox();
        checkUcraniano = new javax.swing.JCheckBox();
        checkTurco = new javax.swing.JCheckBox();
        checkEspanhol = new javax.swing.JCheckBox();
        checkRusso = new javax.swing.JCheckBox();
        checkPolaco = new javax.swing.JCheckBox();
        checkChines = new javax.swing.JCheckBox();
        checkJapones = new javax.swing.JCheckBox();
        checkFrances = new javax.swing.JCheckBox();
        checkAlemao = new javax.swing.JCheckBox();
        checkGrego = new javax.swing.JCheckBox();
        checkArabe = new javax.swing.JCheckBox();
        checkCoreano = new javax.swing.JCheckBox();
        btnProximo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Competências Linguísticas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Línguas Faladas");

        painelLinguas.setLayout(new java.awt.GridLayout(3, 4));

        checkPortugues.setText("Português");
        checkPortugues.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        painelLinguas.add(checkPortugues);

        checkIngles.setText("English");
        painelLinguas.add(checkIngles);

        checkItaliano.setText("Italiano");
        painelLinguas.add(checkItaliano);

        checkUcraniano.setText("Українська (Ukrainska)");
        checkUcraniano.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        painelLinguas.add(checkUcraniano);

        buttonGroup1.add(checkTurco);
        checkTurco.setText("Türkçe");
        checkTurco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        painelLinguas.add(checkTurco);

        checkEspanhol.setText("Espanõl");
        checkEspanhol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        painelLinguas.add(checkEspanhol);

        checkRusso.setText("Русский (Russkiy)");
        painelLinguas.add(checkRusso);

        checkPolaco.setText("Polski");
        painelLinguas.add(checkPolaco);

        checkChines.setText("普通话 (Pǔtōnghuà)");
        painelLinguas.add(checkChines);

        checkJapones.setText("日本語 (Nihongo)");
        painelLinguas.add(checkJapones);

        checkFrances.setText("Français");
        painelLinguas.add(checkFrances);

        checkAlemao.setText("Deutsch");
        painelLinguas.add(checkAlemao);

        checkGrego.setText("Ελληνικά (Elliniká)");
        painelLinguas.add(checkGrego);

        checkArabe.setText("العربية (Al-‘Arabīyah)");
        painelLinguas.add(checkArabe);

        checkCoreano.setText("한국어 (Hangugeo)");
        painelLinguas.add(checkCoreano);

        btnProximo.setText("Próximo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLinguas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(99, 99, 99)
                                .addComponent(btnProximo)
                                .addGap(252, 252, 252))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(painelLinguas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnGuardar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < listaOpcoes.size(); i++) {
            if(listaOpcoes.get(i).isSelected()){
                user.getDados().getLinguas().add(listaOpcoes.get(i).getText());
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnProximo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JCheckBox checkAlemao;
    private javax.swing.JCheckBox checkArabe;
    private javax.swing.JCheckBox checkChines;
    private javax.swing.JCheckBox checkCoreano;
    private javax.swing.JCheckBox checkEspanhol;
    private javax.swing.JCheckBox checkFrances;
    private javax.swing.JCheckBox checkGrego;
    private javax.swing.JCheckBox checkIngles;
    private javax.swing.JCheckBox checkItaliano;
    private javax.swing.JCheckBox checkJapones;
    private javax.swing.JCheckBox checkPolaco;
    private javax.swing.JCheckBox checkPortugues;
    private javax.swing.JCheckBox checkRusso;
    private javax.swing.JCheckBox checkTurco;
    private javax.swing.JCheckBox checkUcraniano;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel painelLinguas;
    // End of variables declaration//GEN-END:variables
}
