/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package curriculum.vitae.gui;

import curriculum.vitae.core.Lingua;
import curriculum.vitae.core.Utilizador;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author joaob
 */
public class adicionarLinguas extends java.awt.Dialog {

    CurriculumVitae cv;
    int index;
    Lingua lingua = new Lingua("", "");
    ArrayList<JButton> buttons = new ArrayList<>();
    String auxLingua = "";

    /**
     * Creates new form adicionarDados
     */
    public adicionarLinguas(CurriculumVitae parent, boolean modal, int index) {
        super(parent, modal);
        this.cv = parent;
        this.index = index;
        initComponents();
        lbl_linguas.setText(cv.listUsers.get(index).getDados().getLinguas().toString());
        buttons.add(pt);
        buttons.add(en);
        buttons.add(it);
        buttons.add(uk);
        buttons.add(tr);
        buttons.add(es);
        buttons.add(ru);
        buttons.add(pl);
        buttons.add(ch);
        buttons.add(jp);
        buttons.add(fr);
        buttons.add(nl);
        buttons.add(gr);
        buttons.add(ar);
        buttons.add(kr);

        for (JButton button : buttons) {
            button.addActionListener(e -> {
                // Capturar o botão que disparou o evento
                JButton clickedButton = (JButton) e.getSource();

                // Atribuir a língua com base no texto do botão clicado
                lingua.setLingua(clickedButton.getText());

                // Chamar a função de redirecionamento
                redireciona();
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_linguas = new javax.swing.JLabel();
        painelLinguas = new javax.swing.JPanel();
        pt = new javax.swing.JButton();
        en = new javax.swing.JButton();
        it = new javax.swing.JButton();
        uk = new javax.swing.JButton();
        tr = new javax.swing.JButton();
        es = new javax.swing.JButton();
        ru = new javax.swing.JButton();
        pl = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        jp = new javax.swing.JButton();
        fr = new javax.swing.JButton();
        nl = new javax.swing.JButton();
        gr = new javax.swing.JButton();
        ar = new javax.swing.JButton();
        kr = new javax.swing.JButton();
        btnVerPerfil = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Competências Linguísticas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Línguas Faladas (selecione a pretendida)");

        lbl_linguas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_linguas.setToolTipText("");

        painelLinguas.setLayout(new java.awt.GridLayout(3, 4));

        pt.setText("Português");
        painelLinguas.add(pt);

        en.setText("English");
        painelLinguas.add(en);

        it.setText("Italiano");
        painelLinguas.add(it);

        uk.setText("Українська (Ukrainska)");
        painelLinguas.add(uk);

        tr.setText("Türkçe");
        painelLinguas.add(tr);

        es.setText("Espanõl");
        painelLinguas.add(es);

        ru.setText("Русский (Russkiy)");
        painelLinguas.add(ru);

        pl.setText("Polski");
        painelLinguas.add(pl);

        ch.setText("普通话 (Pǔtōnghuà)");
        painelLinguas.add(ch);

        jp.setText("日本語 (Nihongo)");
        painelLinguas.add(jp);

        fr.setText("Français");
        painelLinguas.add(fr);

        nl.setText("Deutsch");
        painelLinguas.add(nl);

        gr.setText("Ελληνικά (Elliniká)");
        painelLinguas.add(gr);

        ar.setText("العربية (Al-‘Arabīyah)");
        painelLinguas.add(ar);

        kr.setText("한국어 (Hangugeo)");
        painelLinguas.add(kr);

        btnVerPerfil.setText("Ver Perfil");
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLinguas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(36, 36, 36)
                                .addComponent(btnVerPerfil)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_linguas)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_linguas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(painelLinguas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerPerfil)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed
        // TODO add your handling code here:
        new perfilUser(cv, true, index).setVisible(true);
    }//GEN-LAST:event_btnVerPerfilActionPerformed

    private void redireciona() {
        dispose();
        new AdicionarCompetenciaLinguistica(cv, true, index, lingua).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton ch;
    private javax.swing.JButton en;
    private javax.swing.JButton es;
    private javax.swing.JButton fr;
    private javax.swing.JButton gr;
    private javax.swing.JButton it;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jp;
    private javax.swing.JButton kr;
    private javax.swing.JLabel lbl_linguas;
    private javax.swing.JButton nl;
    private javax.swing.JPanel painelLinguas;
    private javax.swing.JButton pl;
    private javax.swing.JButton pt;
    private javax.swing.JButton ru;
    private javax.swing.JButton tr;
    private javax.swing.JButton uk;
    // End of variables declaration//GEN-END:variables
}
