/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package curriculum.vitae.gui;

import curriculum.vitae.core.RegistoCertificado;
import curriculum.vitae.core.Instituto;
import curriculum.vitae.core.Utilizador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.security.Security;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import utils.Recursos;

/**
 *
 * @author joaob
 */
public class CurriculumVitae extends javax.swing.JFrame {

    ArrayList<Utilizador> listUsers = new ArrayList<>();
    ArrayList<Instituto> listInst = new ArrayList<>();
    RegistoCertificado registoCerti = new RegistoCertificado();
    String basePath = new File("").getAbsolutePath();
    String pathUsers = basePath + "/resources/utilizadores/users.user";
    String pathInst = basePath + "/resources/institutos/institutos.inst";
    String pathBlockchain = basePath + "/resources/blockchain/blockchain.bc";
    File fichUsers;
    File fichInst;
    File fichRegisto;

    /**
     * Creates new form PaginaInicial
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.io.IOException
     */
    public CurriculumVitae() throws ClassNotFoundException, IOException, Exception {
        initComponents();
        Security.addProvider(new BouncyCastleProvider());
        fichUsers = new File(pathUsers);
        fichInst = new File(pathInst);
        fichRegisto = new File(pathBlockchain);
        listUsers = (ArrayList<Utilizador>) Recursos.readObject(fichUsers.getAbsolutePath());
        listInst = (ArrayList<Instituto>) Recursos.readObject(fichInst.getAbsolutePath());
        registoCerti = (RegistoCertificado) Recursos.readObject(fichRegisto.getAbsolutePath());
        //Fecha a janela principal da aplicação e encerra a aplicação
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //Vai guardar a lista de todos os utilizadores durante a atividade no sistema.
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    Recursos.writeObject(listUsers, fichUsers.getAbsolutePath());
                    System.out.println("Lista de Utilizadores gravada com sucesso");
                } catch (Exception ex) {
                    System.err.println("Erro ao gravar a lista de Utilizadores = " + ex.getMessage());
                }

                try {
                    Recursos.writeObject(listInst, fichInst.getAbsolutePath());
                    System.out.println("Lista de Institutos gravada com sucesso");
                } catch (Exception ex) {
                    System.err.println("Erro ao gravar a lista de Institutos = " + ex.getMessage());
                }

                try {
                    Recursos.writeObject(registoCerti, fichRegisto.getAbsolutePath());
                    System.out.println("Blockchain gravada com sucesso");
                } catch (Exception ex) {
                    System.err.println("Erro ao gravar a blockchain = " + ex.getMessage());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCriarCurriculum = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        btnBlockChain = new javax.swing.JButton();

        setTitle("Página Inicial");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum/vitae/images/CV.jpeg"))); // NOI18N

        btnCriarCurriculum.setBackground(new java.awt.Color(86, 137, 171));
        btnCriarCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarCurriculum.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarCurriculum.setText("Cria o teu Curriculum Vitae aqui!!");
        btnCriarCurriculum.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCriarCurriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCurriculumActionPerformed(evt);
            }
        });

        btnAboutUs.setBackground(new java.awt.Color(86, 137, 171));
        btnAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setText("About Us");
        btnAboutUs.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        btnBlockChain.setBackground(new java.awt.Color(86, 137, 171));
        btnBlockChain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBlockChain.setForeground(new java.awt.Color(255, 255, 255));
        btnBlockChain.setText("Blockchain");
        btnBlockChain.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnBlockChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlockChainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBlockChain, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCriarCurriculum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCriarCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBlockChain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarCurriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCurriculumActionPerformed
        // TODO add your handling code here:
        new Login(this, true).setVisible(true);
    }//GEN-LAST:event_btnCriarCurriculumActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        new aboutUs(this, true).setVisible(true);
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnBlockChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlockChainActionPerformed
        // TODO add your handling code here:
        new Blockchain(this, true).setVisible(true);
    }//GEN-LAST:event_btnBlockChainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurriculumVitae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurriculumVitae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurriculumVitae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurriculumVitae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CurriculumVitae().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CurriculumVitae.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CurriculumVitae.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(CurriculumVitae.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnBlockChain;
    private javax.swing.JButton btnCriarCurriculum;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
